# Generated by Django 4.2.29 on 2026-04-04 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answers', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
