# Generated by Django 4.2.29 on 2026-04-04 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useronboarding_customuser_has_completed_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
