# Generated by Django 4.2.30 on 2026-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronboarding',
            name='attention_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='capacity_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='control_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='endurance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
