# Generated by Django 4.2.30 on 2026-05-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useronboarding_attention_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveBaselineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_score', models.FloatField()),
                ('capacity_score', models.IntegerField()),
                ('control_score', models.FloatField()),
                ('endurance_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_baseline_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
